packageName: naurt_api
packageVersion: 0.1.1

enumClassPrefix: true
isGoSubmodule: false
withGoMod: true
disallowAdditionalPropertiesIfNotPresent: false
generateUnmarshalJSON: true
generateInterfaces: true

gitUserId: Naurt-Ltd
gitRepoId: api_specification/generated/go
